export const CHANNEL = [
  {
    id: 1,
    title: "React Course",
    user: "Bro Code",
    views: "171k",
    posted: "1 months ago",
  },
  {
    id: 2,
    title: "java Course",
    user: "Code With Harry",
    views: "200k",
    posted: "11 months ago",
  },
  {
    id: 3,
    title: "Python Course",
    user: "Chai Aur Code",
    views: "500K",
    posted: "1 year ago",
  },
  {
    id: 4,
    title: "JavaScript Course",
    user: "Bro Code",
    views: "400k",
    posted: "6 months ago",
  },
  {
    id: 5,
    title: "Flutter Course",
    user: "Bro Code",
    views: "800K",
    posted: "9 months ago",
  },
  {
    id: 6,
    title: "MERN Stack Course",
    user: "Programming with Mosh",
    views: "171k",
    posted: "1 months ago",
  },
  {
    id: 7,
    title: "Django Course",
    user: "Bro Code",
    views: "671k",
    posted: "1 year ago",
  },
  {
    id: 8,
    title: "Angular Course",
    user: "Programming with Mosh",
    views: "971k",
    posted: "8 months ago",
  },
  {
    id: 9,
    title: "JavaScript Course",
    user: "Neeraj Walia",
    views: "471k",
    posted: "10 months ago",
  },
  {
    id: 10,
    title: "ReactNative Course",
    user: "Apna College",
    views: "571k",
    posted: "6 months ago",
  },
];
